import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 20, 2014, 9:16:11 PM
 */

/**
 *
 * @author Akash Chauhan.
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Itempurchase = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        Confirmpurchase = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        OptionsDialog = new javax.swing.JDialog();
        CrRAButton = new javax.swing.JRadioButton();
        ElRAButton = new javax.swing.JRadioButton();
        GaRAButton = new javax.swing.JRadioButton();
        SpRAButton = new javax.swing.JRadioButton();
        FuRAButton = new javax.swing.JRadioButton();
        VeRAButton = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ChineseDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        CT = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ct1 = new javax.swing.JTextField();
        ct2 = new javax.swing.JTextField();
        CB2 = new javax.swing.JButton();
        CB1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        IndianTypicalDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ET = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        et1 = new javax.swing.JTextField();
        et2 = new javax.swing.JTextField();
        EB1 = new javax.swing.JButton();
        EB2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SouthIndianDialog = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        FT = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ft1 = new javax.swing.JTextField();
        ft2 = new javax.swing.JTextField();
        FB1 = new javax.swing.JButton();
        FB2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        PizzaDilog = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        ST = new javax.swing.JTable();
        st1 = new javax.swing.JTextField();
        st2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SB1 = new javax.swing.JButton();
        SB2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        BeveragesDialog = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        GT = new javax.swing.JTable();
        gt1 = new javax.swing.JTextField();
        gt2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GB1 = new javax.swing.JButton();
        GB2 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        NonVegDialog = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        VT = new javax.swing.JTable();
        vt1 = new javax.swing.JTextField();
        vt2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        VB1 = new javax.swing.JButton();
        VB2 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        TransactionDialog = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        cm = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtj1 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ENTERname = new javax.swing.JTextField();
        TransactionID = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        Itempurchase.setMinimumSize(new java.awt.Dimension(800, 600));
        Itempurchase.getContentPane().setLayout(null);

        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Itemcode", "Item Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ItemTable.setOpaque(false);
        jScrollPane3.setViewportView(ItemTable);

        Itempurchase.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(170, 70, 452, 180);

        Confirmpurchase.setText("Confirm Purchase");
        Confirmpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmpurchaseActionPerformed(evt);
            }
        });
        Itempurchase.getContentPane().add(Confirmpurchase);
        Confirmpurchase.setBounds(180, 320, 190, 60);

        jLabel2.setText("Your Cart");
        Itempurchase.getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 30, 130, 20);

        jButton1.setText("Go hunting");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Itempurchase.getContentPane().add(jButton1);
        jButton1.setBounds(460, 320, 160, 60);

        jLabel19.setIcon(new javax.swing.ImageIcon("G:\\Project\\images\\food-wallpaper-phone-For-Desktop-Wallpaper.jpg")); // NOI18N
        Itempurchase.getContentPane().add(jLabel19);
        jLabel19.setBounds(-1140, -250, 2260, 870);

        OptionsDialog.setMinimumSize(new java.awt.Dimension(1100, 680));
        OptionsDialog.getContentPane().setLayout(null);

        CrRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/chinese 1.png"))); // NOI18N
        CrRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(CrRAButton);
        CrRAButton.setBounds(10, 440, 490, 130);

        ElRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/stock-vector-black-grunge-rubber-stamp-with-hinduism-symbol-and-the-text-indian-food-written-inside-vector-163737032.jpg"))); // NOI18N
        ElRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(ElRAButton);
        ElRAButton.setBounds(600, 240, 380, 150);

        GaRAButton.setBackground(new java.awt.Color(255, 255, 255));
        GaRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/bev.png"))); // NOI18N
        GaRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(GaRAButton);
        GaRAButton.setBounds(605, 60, 370, 130);

        SpRAButton.setBackground(new java.awt.Color(255, 255, 255));
        SpRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/pizza12.png"))); // NOI18N
        SpRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(SpRAButton);
        SpRAButton.setBounds(10, 60, 490, 130);

        FuRAButton.setBackground(new java.awt.Color(0, 0, 0));
        FuRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/South_Indieslogo_1432705822.png"))); // NOI18N
        FuRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(FuRAButton);
        FuRAButton.setBounds(0, 240, 500, 150);

        VeRAButton.setBackground(new java.awt.Color(255, 255, 255));
        VeRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/nonveg1.png"))); // NOI18N
        VeRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(VeRAButton);
        VeRAButton.setBounds(600, 440, 380, 130);

        jButton4.setText("Cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(jButton4);
        jButton4.setBounds(980, 10, 80, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/black-wallpaper-30.jpg"))); // NOI18N
        OptionsDialog.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1110, 650);

        ChineseDialog.setMinimumSize(new java.awt.Dimension(900, 700));
        ChineseDialog.getContentPane().setLayout(null);

        CT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CT);

        ChineseDialog.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 210, 560, 120);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel5.setText("Enter Product no. to purchase");
        ChineseDialog.getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 370, 240, 30);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel6.setText("Quantity");
        ChineseDialog.getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 430, 100, 19);

        ct1.setText("CC");
        ChineseDialog.getContentPane().add(ct1);
        ct1.setBounds(550, 370, 110, 30);
        ChineseDialog.getContentPane().add(ct2);
        ct2.setBounds(550, 430, 110, 30);

        CB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB2ActionPerformed(evt);
            }
        });
        ChineseDialog.getContentPane().add(CB2);
        CB2.setBounds(250, 510, 170, 70);

        CB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        CB1.setText("Purchase");
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        ChineseDialog.getContentPane().add(CB1);
        CB1.setBounds(500, 510, 200, 70);

        jButton5.setText("Cart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ChineseDialog.getContentPane().add(jButton5);
        jButton5.setBounds(740, 10, 90, 23);

        jLabel21.setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        jLabel21.setText("Please Choose Your Product");
        ChineseDialog.getContentPane().add(jLabel21);
        jLabel21.setBounds(350, 170, 320, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/ba8ff758015bb0a302818034b93ae20d_most-helpful-guy-chinese-food_1170-400_1.jpeg"))); // NOI18N
        ChineseDialog.getContentPane().add(jLabel20);
        jLabel20.setBounds(-140, 0, 1110, 360);

        IndianTypicalDialog.setMinimumSize(new java.awt.Dimension(950, 680));
        IndianTypicalDialog.getContentPane().setLayout(null);

        ET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ET);

        IndianTypicalDialog.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 220, 510, 140);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Enter Product no. to purchase");
        IndianTypicalDialog.getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 370, 230, 30);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Quantity");
        IndianTypicalDialog.getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 450, 100, 20);

        et1.setText("I");
        IndianTypicalDialog.getContentPane().add(et1);
        et1.setBounds(560, 370, 170, 40);
        IndianTypicalDialog.getContentPane().add(et2);
        et2.setBounds(560, 440, 170, 30);

        EB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        EB1.setText("Purchase");
        EB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EB1ActionPerformed(evt);
            }
        });
        IndianTypicalDialog.getContentPane().add(EB1);
        EB1.setBounds(560, 510, 180, 69);

        EB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        EB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EB2ActionPerformed(evt);
            }
        });
        IndianTypicalDialog.getContentPane().add(EB2);
        EB2.setBounds(230, 510, 180, 70);

        jButton6.setText("Cart");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        IndianTypicalDialog.getContentPane().add(jButton6);
        jButton6.setBounds(810, 10, 100, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/dk_logo_yellow_blue_1.png"))); // NOI18N
        IndianTypicalDialog.getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 10, 790, 190);

        jLabel26.setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        jLabel26.setForeground(new java.awt.Color(204, 255, 204));
        jLabel26.setText("Please Choose Your Product");
        IndianTypicalDialog.getContentPane().add(jLabel26);
        jLabel26.setBounds(360, 150, 340, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon("G:\\Project\\images\\Indian-food.jpg")); // NOI18N
        IndianTypicalDialog.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 1060, 630);

        SouthIndianDialog.setMinimumSize(new java.awt.Dimension(950, 650));
        SouthIndianDialog.getContentPane().setLayout(null);

        FT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(FT);

        SouthIndianDialog.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(180, 170, 490, 130);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Enter Product no. to purchase");
        SouthIndianDialog.getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 330, 230, 19);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Quantity");
        SouthIndianDialog.getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 380, 80, 30);

        ft1.setText("S");
        SouthIndianDialog.getContentPane().add(ft1);
        ft1.setBounds(520, 320, 120, 30);
        SouthIndianDialog.getContentPane().add(ft2);
        ft2.setBounds(520, 380, 120, 30);

        FB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        FB1.setText("Purchase");
        FB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FB1ActionPerformed(evt);
            }
        });
        SouthIndianDialog.getContentPane().add(FB1);
        FB1.setBounds(460, 480, 190, 70);

        FB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        FB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FB2ActionPerformed(evt);
            }
        });
        SouthIndianDialog.getContentPane().add(FB2);
        FB2.setBounds(210, 480, 180, 70);

        jLabel29.setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        jLabel29.setForeground(new java.awt.Color(102, 255, 102));
        jLabel29.setText("Please Choose Your Product");
        SouthIndianDialog.getContentPane().add(jLabel29);
        jLabel29.setBounds(240, 110, 310, 40);

        jButton7.setText("Cart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        SouthIndianDialog.getContentPane().add(jButton7);
        jButton7.setBounds(680, 10, 80, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon("G:\\Project\\images\\south-indian-food.jpg")); // NOI18N
        SouthIndianDialog.getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 0, 1100, 630);

        PizzaDilog.setMinimumSize(new java.awt.Dimension(970, 600));
        PizzaDilog.getContentPane().setLayout(null);

        ST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(ST);

        PizzaDilog.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(90, 130, 520, 140);

        st1.setText("P");
        PizzaDilog.getContentPane().add(st1);
        st1.setBounds(430, 300, 140, 30);

        st2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st2ActionPerformed(evt);
            }
        });
        PizzaDilog.getContentPane().add(st2);
        st2.setBounds(430, 350, 140, 30);

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 1, 14));
        jLabel11.setText("Enter Product no. to Purchase");
        PizzaDilog.getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 300, 280, 30);

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14));
        jLabel12.setText("Quantity");
        PizzaDilog.getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 350, 90, 20);

        SB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        SB1.setText("Purchase");
        SB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SB1ActionPerformed(evt);
            }
        });
        PizzaDilog.getContentPane().add(SB1);
        SB1.setBounds(430, 430, 180, 69);

        SB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        SB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SB2ActionPerformed(evt);
            }
        });
        PizzaDilog.getContentPane().add(SB2);
        SB2.setBounds(100, 430, 180, 70);

        jLabel31.setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        jLabel31.setText("Please Choose Your Product");
        PizzaDilog.getContentPane().add(jLabel31);
        jLabel31.setBounds(200, 50, 320, 50);

        jButton8.setText("Cart");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        PizzaDilog.getContentPane().add(jButton8);
        jButton8.setBounds(633, 23, 90, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Greeka.jpg"))); // NOI18N
        PizzaDilog.getContentPane().add(jLabel25);
        jLabel25.setBounds(0, -110, 1100, 730);

        BeveragesDialog.setMinimumSize(new java.awt.Dimension(900, 600));
        BeveragesDialog.getContentPane().setLayout(null);

        GT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(GT);

        BeveragesDialog.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(160, 100, 452, 130);

        gt1.setText("B");
        gt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gt1ActionPerformed(evt);
            }
        });
        BeveragesDialog.getContentPane().add(gt1);
        gt1.setBounds(500, 260, 110, 40);
        BeveragesDialog.getContentPane().add(gt2);
        gt2.setBounds(500, 320, 110, 40);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel13.setForeground(new java.awt.Color(102, 51, 255));
        jLabel13.setText("Enter Product no. to Purchase");
        BeveragesDialog.getContentPane().add(jLabel13);
        jLabel13.setBounds(160, 270, 230, 40);

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel14.setForeground(new java.awt.Color(51, 0, 255));
        jLabel14.setText("Quantity");
        BeveragesDialog.getContentPane().add(jLabel14);
        jLabel14.setBounds(250, 330, 90, 20);

        GB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        GB1.setText("Purchase");
        GB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GB1ActionPerformed(evt);
            }
        });
        BeveragesDialog.getContentPane().add(GB1);
        GB1.setBounds(420, 370, 190, 70);

        GB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        GB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GB2ActionPerformed(evt);
            }
        });
        BeveragesDialog.getContentPane().add(GB2);
        GB2.setBounds(170, 370, 180, 70);

        jLabel35.setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Please Choose Your Product");
        BeveragesDialog.getContentPane().add(jLabel35);
        jLabel35.setBounds(220, 40, 340, 50);

        jButton9.setText("Cart");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        BeveragesDialog.getContentPane().add(jButton9);
        jButton9.setBounds(650, 20, 70, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/bev.jpg"))); // NOI18N
        BeveragesDialog.getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 990, 520);

        NonVegDialog.setMinimumSize(new java.awt.Dimension(800, 600));
        NonVegDialog.getContentPane().setLayout(null);

        VT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(VT);

        NonVegDialog.getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(190, 90, 452, 110);

        vt1.setText("N");
        NonVegDialog.getContentPane().add(vt1);
        vt1.setBounds(500, 230, 140, 40);
        NonVegDialog.getContentPane().add(vt2);
        vt2.setBounds(500, 300, 140, 40);

        jLabel15.setFont(new java.awt.Font("Kristen ITC", 2, 18));
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Enter Product no. to Purchase");
        NonVegDialog.getContentPane().add(jLabel15);
        jLabel15.setBounds(190, 240, 320, 30);

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 2, 24));
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("Quantity");
        NonVegDialog.getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 300, 140, 40);

        VB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        VB1.setText("Purchase");
        VB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VB1ActionPerformed(evt);
            }
        });
        NonVegDialog.getContentPane().add(VB1);
        VB1.setBounds(440, 450, 200, 70);

        VB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        VB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VB2ActionPerformed(evt);
            }
        });
        NonVegDialog.getContentPane().add(VB2);
        VB2.setBounds(170, 450, 180, 70);

        jLabel46.setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        jLabel46.setForeground(new java.awt.Color(51, 0, 51));
        jLabel46.setText("Please Choose your Product");
        NonVegDialog.getContentPane().add(jLabel46);
        jLabel46.setBounds(270, 20, 330, 60);

        jButton10.setText("Cart");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        NonVegDialog.getContentPane().add(jButton10);
        jButton10.setBounds(660, 10, 90, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/dc-Cover-ro5laha4iudcuiqodd85rau0o1-20160611005126.Medi.jpeg"))); // NOI18N
        NonVegDialog.getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 0, 820, 440);

        TransactionDialog.setMinimumSize(new java.awt.Dimension(800, 600));
        TransactionDialog.getContentPane().setLayout(null);

        cm.setColumns(20);
        cm.setRows(5);
        jScrollPane8.setViewportView(cm);

        TransactionDialog.getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(60, 190, 440, 250);

        jLabel17.setFont(new java.awt.Font("Segoe Script", 3, 11));
        jLabel17.setText("CASH-MEMO");
        TransactionDialog.getContentPane().add(jLabel17);
        jLabel17.setBounds(210, 130, 130, 60);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TransactionDialog.getContentPane().add(jButton2);
        jButton2.setBounds(630, 20, 120, 40);

        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        TransactionDialog.getContentPane().add(jButton3);
        jButton3.setBounds(600, 510, 130, 40);

        jLabel3.setText("Enter your address");
        TransactionDialog.getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 240, 220, 30);

        jtj1.setColumns(20);
        jtj1.setRows(5);
        jScrollPane9.setViewportView(jtj1);

        TransactionDialog.getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(540, 280, 240, 160);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/rov0G8.jpg"))); // NOI18N
        TransactionDialog.getContentPane().add(jLabel30);
        jLabel30.setBounds(0, 0, 810, 640);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24));
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Please Enter your name to generate your session ID!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 220, 750, 50);
        getContentPane().add(ENTERname);
        ENTERname.setBounds(350, 300, 160, 30);

        TransactionID.setText("Generate Transaction  ID");
        TransactionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionIDActionPerformed(evt);
            }
        });
        getContentPane().add(TransactionID);
        TransactionID.setBounds(300, 360, 250, 70);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/food-art-picture-For-Desktop-Wallpaper.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(-280, -20, 1500, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Calendar p = Calendar.getInstance();
  		 int day = p.get(Calendar.DATE);
   		 int month = p.get(Calendar.MONTH) + 1;
   		 int year = p.get(Calendar.YEAR);
 int hour = p.get(Calendar.HOUR);
  		 int minute = p.get(Calendar.MINUTE);
   		 String z = day + "_" + month + "_" + year + "_" + hour + "_" + minute;

    private void TransactionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionIDActionPerformed

        String na = ENTERname.getText();
        String Ta = na + z;
        

        if (na.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Name to Generate Session ID");
        }
        else {
            String w = na + hour + ":" + minute + "  " + day + "/" + month + "/" + year;
             JOptionPane.showMessageDialog(null, "Your ID is "+w);
            Itempurchase.setVisible(true);
            
            
        }

        try {
            Class.forName("java.sql.Driver");
            Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
            Statement s = d.createStatement();

            String q = "create table  " + Ta + " (itemcode varchar(10), itemname varchar(20), price int(10), qty int(10));";

            s.executeUpdate(q);
        }
             catch (Exception e) { System.out.println(e.getMessage());}

             
        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionIDActionPerformed

    private void CrRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrRAButtonActionPerformed
ChineseDialog.setVisible(true);

try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food","root", "123");
            Statement s = c.createStatement();
            String q = "select * from chinese ";
            ResultSet rs = s.executeQuery(q);
 DefaultTableModel dtm = (DefaultTableModel) CT.getModel();
     while (rs.next()) {
                String n = rs.getString("Cname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");

                dtm.addRow(new Object[]{k, n, a});
                CrRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_CrRAButtonActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from chinese ";
            ResultSet rs = s.executeQuery(q);

            int tpe = CT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = ct2.getText();
            String pe = ct1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);

            int pe3 = Integer.parseInt(j);
            if (ct1.getText().equals("CC")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        ct1.setText("CC");
                        ct2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Cname");
                        int a = rs.getInt("price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});
                        ct1.setText("");
                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                        Statement x = d.createStatement();
                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + ");";
                         x.executeUpdate(r);

                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CB1ActionPerformed

    private void CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB2ActionPerformed
       DefaultTableModel dtm1 = (DefaultTableModel) CT.getModel();
        int row= dtm1.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm1.removeRow(0);
        ChineseDialog.dispose();
        CrRAButton.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_CB2ActionPerformed

    private void ElRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElRAButtonActionPerformed
        IndianTypicalDialog.setVisible(true);
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from indian ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) ET.getModel();
            while (rs.next()) {
                String n = rs.getString("Iname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");
                
                dtm.addRow(new Object[]{k, n, a});
                ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ElRAButtonActionPerformed

    private void EB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EB2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) ET.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        IndianTypicalDialog.dispose();
        ElRAButton.setSelected(false);

        // TODO add your handling code here:
}//GEN-LAST:event_EB2ActionPerformed

    private void EB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from indian ";
            ResultSet rs = s.executeQuery(q);
            String na = ENTERname.getText();
            String Ta = na + z;
            int tpe = ET.getRowCount();
            String j = et2.getText();
            String pe = et1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);
            if (et1.getText().equals("I")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    }
                    if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        et1.setText("I");
                        et2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Iname");
                        int a = rs.getInt("price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                        Statement x = d.createStatement();
                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + ");";
                        x.executeUpdate(r);
                       }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EB1ActionPerformed

    private void FuRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuRAButtonActionPerformed
          SouthIndianDialog.setVisible(true);
            try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from sind ";
            ResultSet rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) FT.getModel();
            while (rs.next()) {

            String n = rs.getString("Sname");
            String k = rs.getString("ProductNo");
            int a = rs.getInt("price");


                dtm.addRow(new Object[]{k, n, a});
                FuRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_FuRAButtonActionPerformed

    private void FB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FB1ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from sind ";
            ResultSet rs = s.executeQuery(q);

            int tpe = FT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = ft2.getText();
            String pe = ft1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);
            if (ft1.getText().equals("S")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        ft1.setText("S");
                        ft2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Sname");
                        int a = rs.getInt("price");
                       // int qty= rs.getInt("qty");
                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + "); ";
                       x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_FB1ActionPerformed

    private void FB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FB2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) FT.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        SouthIndianDialog.dispose();
        FuRAButton.setSelected(false);

        // TODO add your handling code here:
}//GEN-LAST:event_FB2ActionPerformed

    private void SpRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpRAButtonActionPerformed
PizzaDilog.setVisible(true);
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from pizza ";
            ResultSet rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) ST.getModel();
            while (rs.next()) {
                String n = rs.getString("Sname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");

                dtm.addRow(new Object[]{k, n, a});
                SpRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SpRAButtonActionPerformed

    private void SB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SB2ActionPerformed
          DefaultTableModel dtm = (DefaultTableModel) ST.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        PizzaDilog.dispose();
        SpRAButton.setSelected(false);
     // TODO add your handling code here:
    }//GEN-LAST:event_SB2ActionPerformed

    private void SB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from pizza ";
            ResultSet rs = s.executeQuery(q);
            String na = ENTERname.getText();
            String Ta = na + z;
            int tpe = ST.getRowCount();
            String j = st2.getText();
            String pe = st1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);

            if (st1.getText().equals("P")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        st1.setText("P");
                        st2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Sname");
                        int a = rs.getInt("price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + ");";
                        x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SB1ActionPerformed

    private void GaRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaRAButtonActionPerformed
            BeveragesDialog.setVisible(true);
            try {
                Class.forName("java.sql.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
                Statement s = c.createStatement();
                String q = "select * from beverage ";
                ResultSet rs = s.executeQuery(q);

                DefaultTableModel dtm2 = (DefaultTableModel) GT.getModel();
                while (rs.next()) {
                    String n = rs.getString("Bname");
                    String k = rs.getString("ProductNo");
                    int a = rs.getInt("price");
                   
                    dtm2.addRow(new Object[]{k, n, a});
                    GaRAButton.setSelected(false);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_GaRAButtonActionPerformed

    private void GB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from beverage ";
            ResultSet rs = s.executeQuery(q);

            int tpe = GT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = gt2.getText();
            String pe = gt1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);

            if (gt1.getText().equals("B")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        gt1.setText("B");
                        gt2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("Productno");
                        String n = rs.getString("Bname");
                        int a = rs.getInt("price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});
                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values('" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + "); ";
                        x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_GB1ActionPerformed

    private void GB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GB2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) GT.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        BeveragesDialog.dispose();
        GaRAButton.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_GB2ActionPerformed

    private void VeRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeRAButtonActionPerformed
            NonVegDialog.setVisible(true);
            try {
                Class.forName("java.sql.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
                Statement s = c.createStatement();
                String q = "select * from nonveg ";
                ResultSet rs = s.executeQuery(q);

                DefaultTableModel dtm = (DefaultTableModel) VT.getModel();
                while (rs.next()) {
                    String n = rs.getString("Vname");
                    String k = rs.getString("ProductNo");
                    int a = rs.getInt("price");

                    dtm.addRow(new Object[]{k, n, a});
                    VeRAButton.setSelected(false);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_VeRAButtonActionPerformed

    private void VB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from nonveg ";
            ResultSet rs = s.executeQuery(q);

            int tpe = VT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = vt2.getText();
            String pe = vt1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);

            if (vt1.getText().equals("NV")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        vt1.setText("NV");
                        vt2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Vname");
                        int a = rs.getInt("price");

                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + "); ";
                        x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_VB1ActionPerformed

    private void VB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VB2ActionPerformed
         DefaultTableModel dtm = (DefaultTableModel) VT.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        NonVegDialog.dispose();
        VeRAButton.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_VB2ActionPerformed

    private void ConfirmpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmpurchaseActionPerformed
        String na = ENTERname.getText();
        String Ta = na + z;
        String w = na + hour + ":" + minute + "  " + day + "/" + month + "/" + year;

        new vendor(Ta).setVisible(true);

        try {
                Class.forName("java.sql.Driver");
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/purchase", "root", "123");
                Statement s = d.createStatement();
                String q = "select * from " + Ta + ";";

                ResultSet rs = s.executeQuery(q);

                ChineseDialog.setVisible(false);
                IndianTypicalDialog.setVisible(false);
                SouthIndianDialog.setVisible(false);
                PizzaDilog.setVisible(false);
                BeveragesDialog.setVisible(false);
                TransactionDialog.setVisible(true);
                cm.setText("");

                cm.append("            Customer Name  :-   " + na);
                cm.append("\n" + "            Customer ID :-   " + w);

                int c, e = 0;
                while (rs.next()) {
                    String g = rs.getString("itemcode");
                    String f = rs.getString("itemname");
                    int a = rs.getInt("price");
                    int b = rs.getInt("qty");
                    c = a * b;
                    e = e + c;
                    cm.append("\n" + "            " + g + "            " + f + " :  Rs.  " + a + " per unit   " + b + "  Units    Net : Rs.     " + c);
                }

                cm.append("\n");
                cm.append("\n");

                cm.append("\n" + "            " + "Total Amount to be paid :- Rs.  " + e);
                cm.append("\n");
                cm.append("\n" + "            Thank You For Shopping. Have a nice day ...      ");
              } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        new vendor(Ta).dispose();
           // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmpurchaseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
OptionsDialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Itempurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Itempurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Itempurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Itempurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Itempurchase.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void st2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st2ActionPerformed

    private void gt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gt1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Itempurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
Itempurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String address=jtj1.getText();
JOptionPane.showMessageDialog(null, "Your Order has been successfully placed! thank you for choosing us!");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BeveragesDialog;
    private javax.swing.JButton CB1;
    private javax.swing.JButton CB2;
    private javax.swing.JTable CT;
    private javax.swing.JDialog ChineseDialog;
    private javax.swing.JButton Confirmpurchase;
    private javax.swing.JRadioButton CrRAButton;
    private javax.swing.JButton EB1;
    private javax.swing.JButton EB2;
    private javax.swing.JTextField ENTERname;
    private javax.swing.JTable ET;
    private javax.swing.JRadioButton ElRAButton;
    private javax.swing.JButton FB1;
    private javax.swing.JButton FB2;
    private javax.swing.JTable FT;
    private javax.swing.JRadioButton FuRAButton;
    private javax.swing.JButton GB1;
    private javax.swing.JButton GB2;
    private javax.swing.JTable GT;
    private javax.swing.JRadioButton GaRAButton;
    private javax.swing.JDialog IndianTypicalDialog;
    private javax.swing.JTable ItemTable;
    private javax.swing.JDialog Itempurchase;
    private javax.swing.JDialog NonVegDialog;
    private javax.swing.JDialog OptionsDialog;
    private javax.swing.JDialog PizzaDilog;
    private javax.swing.JButton SB1;
    private javax.swing.JButton SB2;
    private javax.swing.JTable ST;
    private javax.swing.JDialog SouthIndianDialog;
    private javax.swing.JRadioButton SpRAButton;
    private javax.swing.JDialog TransactionDialog;
    private javax.swing.JButton TransactionID;
    private javax.swing.JButton VB1;
    private javax.swing.JButton VB2;
    private javax.swing.JTable VT;
    private javax.swing.JRadioButton VeRAButton;
    private javax.swing.JTextArea cm;
    private javax.swing.JTextField ct1;
    private javax.swing.JTextField ct2;
    private javax.swing.JTextField et1;
    private javax.swing.JTextField et2;
    private javax.swing.JTextField ft1;
    private javax.swing.JTextField ft2;
    private javax.swing.JTextField gt1;
    private javax.swing.JTextField gt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jtj1;
    private javax.swing.JTextField st1;
    private javax.swing.JTextField st2;
    private javax.swing.JTextField vt1;
    private javax.swing.JTextField vt2;
    // End of variables declaration//GEN-END:variables

}
