import com.mysql.jdbc.DatabaseMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/*
 * vendor.java
 *
 * Created on 15 Apr, 2017, 10:14:01 AM
 */

/**
 *
 * @author hp
 */
public class vendor extends javax.swing.JFrame {
    String username;
    private String ttbm;
    /** Creates new form vendor */
    public vendor() {
        initComponents();
    }

    public vendor(String Ta) {
        username = Ta;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTextArea();
        jt1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menus = new javax.swing.JDialog();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        manage = new javax.swing.JDialog();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        mt = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Add = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Delete = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        mt1 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Update = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(800, 600));
        jDialog1.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 3, 14));
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Pending orders");
        jDialog1.getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 40, 220, 30);

        jta1.setColumns(20);
        jta1.setEditable(false);
        jta1.setRows(5);
        jScrollPane1.setViewportView(jta1);

        jDialog1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 250, 290);

        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jt1);
        jt1.setBounds(470, 70, 100, 40);

        jButton2.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jButton2.setText("View order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2);
        jButton2.setBounds(380, 130, 140, 33);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Enter order number");
        jDialog1.getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 80, 170, 20);

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton7);
        jButton7.setBounds(490, 20, 73, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/3d_colorful_squares-wide.jpg"))); // NOI18N
        jDialog1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 860, 750);

        jDialog2.setMinimumSize(new java.awt.Dimension(800, 600));
        jDialog2.getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Price", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jDialog2.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 80, 452, 210);

        jButton3.setText("Verify and send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton3);
        jButton3.setBounds(190, 320, 150, 30);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton4);
        jButton4.setBounds(520, 10, 80, 30);

        jl1.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jDialog2.getContentPane().add(jl1);
        jl1.setBounds(170, 40, 240, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jLabel5.setText("Customer ID :");
        jDialog2.getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 40, 110, 24);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/hahahaha.jpg"))); // NOI18N
        jDialog2.getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 800, 560);

        menus.setMinimumSize(new java.awt.Dimension(800, 600));
        menus.getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Desi");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(380, 90, 130, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("South Indian");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(140, 150, 130, 40);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Beverages");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(140, 210, 130, 40);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Non Vegetarian");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(380, 210, 130, 40);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Chinese");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(380, 150, 130, 40);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Pizza");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(140, 90, 130, 40);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        menus.getContentPane().add(jButton8);
        jButton8.setBounds(580, 20, 90, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/black-wallpaper-30.jpg"))); // NOI18N
        menus.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 920, 650);

        manage.setMinimumSize(new java.awt.Dimension(800, 600));
        manage.getContentPane().setLayout(null);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Update Price ");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        manage.getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(160, 280, 110, 23);

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("Add");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        manage.getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(400, 280, 80, 23);

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("Delete");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        manage.getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(640, 280, 70, 23);

        mt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product No.", "Prodect Name", "Price", "Quantity "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(mt);

        manage.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(220, 110, 450, 100);

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        manage.getContentPane().add(jButton9);
        jButton9.setBounds(650, 20, 90, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/BestHDWallpapersPack241_1 (22).jpg"))); // NOI18N
        manage.getContentPane().add(jLabel10);
        jLabel10.setBounds(-540, -10, 1690, 810);

        Add.setMinimumSize(new java.awt.Dimension(800, 600));
        Add.getContentPane().setLayout(null);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Product ID");
        Add.getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 70, 110, 30);
        Add.getContentPane().add(jTextField2);
        jTextField2.setBounds(320, 250, 110, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Enter Name");
        Add.getContentPane().add(jLabel13);
        jLabel13.setBounds(120, 130, 80, 30);
        Add.getContentPane().add(jTextField3);
        jTextField3.setBounds(320, 130, 110, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Enter Price");
        Add.getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 190, 110, 30);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Enter Quantity");
        Add.getContentPane().add(jLabel15);
        jLabel15.setBounds(120, 250, 110, 30);
        Add.getContentPane().add(jTextField4);
        jTextField4.setBounds(320, 70, 110, 30);
        Add.getContentPane().add(jTextField5);
        jTextField5.setBounds(320, 190, 110, 30);

        jButton10.setText("ADD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Add.getContentPane().add(jButton10);
        jButton10.setBounds(230, 340, 80, 23);

        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Add.getContentPane().add(jButton11);
        jButton11.setBounds(500, 20, 70, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/black-wallpaper-30.jpg"))); // NOI18N
        Add.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1140, 630);

        Delete.setMinimumSize(new java.awt.Dimension(800, 600));
        Delete.getContentPane().setLayout(null);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enter the Product Id to delete the product!");
        Delete.getContentPane().add(jLabel17);
        jLabel17.setBounds(130, 290, 290, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        Delete.getContentPane().add(jTextField6);
        jTextField6.setBounds(450, 290, 140, 30);

        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Delete.getContentPane().add(jButton12);
        jButton12.setBounds(323, 360, 120, 23);

        mt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Price", "Quantity"
            }
        ));
        jScrollPane4.setViewportView(mt1);

        Delete.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(160, 50, 452, 100);

        jButton13.setText("Back");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Delete.getContentPane().add(jButton13);
        jButton13.setBounds(660, 10, 80, 30);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/black-wallpaper-30.jpg"))); // NOI18N
        Delete.getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 1140, 630);

        Update.setMinimumSize(new java.awt.Dimension(800, 600));
        Update.getContentPane().setLayout(null);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Enter New Price");
        Update.getContentPane().add(jLabel20);
        jLabel20.setBounds(170, 190, 130, 40);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Enter ID");
        Update.getContentPane().add(jLabel22);
        jLabel22.setBounds(170, 100, 130, 40);
        Update.getContentPane().add(jTextField7);
        jTextField7.setBounds(330, 100, 170, 40);
        Update.getContentPane().add(jTextField8);
        jTextField8.setBounds(330, 180, 170, 40);

        jButton14.setText("Update Price");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Update.getContentPane().add(jButton14);
        jButton14.setBounds(240, 270, 140, 30);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Update.getContentPane().add(Back);
        Back.setBounds(580, 20, 80, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/black-wallpaper-30.jpg"))); // NOI18N
        Update.getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 1070, 560);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 470));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vender ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 110, 90, 30);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(300, 190, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 190, 90, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 110, 110, 30);

        jButton1.setText("Check for Orders");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 260, 140, 30);

        jButton5.setText("Manage Menus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 260, 120, 30);

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(423, 20, 80, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/dark-background_1600x1200_468-standard.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 700, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String id= jTextField1.getText();
     String pass = new String(jPasswordField1.getPassword());


     if((id.compareTo("VN71")==0) && (pass.compareTo("password")==0)){

        
    // JOptionPane.showMessageDialog(null, "Welcome");
     jDialog1.setVisible(true);

     int a=0,flag=0;
     int j;


    try{
        Class.forName("com.mysql.jdbc.Driver");

        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/purchase","root","123");

Statement smt= con.createStatement();
  DatabaseMetaData md= (DatabaseMetaData) con.getMetaData();

    ResultSet rs= md.getTables(null,null,"%", null);
    ResultSet rs1 = md.getTables(null, null, "%", null);
 //      for(int i=0; i< rs.getMetaData().getColumnCount(); i++){
   //        types[i]= rs.getString(names);
//}
for(j=0;rs1.next();j++);
 String tables[] = new String[j+1];
  for(j=0;rs.next();j++)
{  tables[j]= rs.getString(3);
       jta1.append("\n");


                jta1.append("\n" + (j+1)+"."+"\t"+ tables[j]);
                jta1.append("\n");
                   //System.out.println(tables[j]);

    //ordername[a]=rs.getString(3);
   // th(nm);
//ordername[a]=nm;
//a++;
}
 /*while(rs2.next())
 {
     System.out.println(rs2);
 }
*/





 //  System.out.print(nm);
    rs.close();
    smt.close();
    con.close();
    }

    catch(Exception e){
       //System.e();
        JOptionPane.showMessageDialog(null, "Error in connectivity");
    System.out.println(e.getMessage());
    }        // TODO add your handling code here:


String ab= jta1.getText();
     if(ab.compareTo("")==0){
        jDialog1.dispose();
         JOptionPane.showMessageDialog(null, "No orders for now");
     }

   
     

}
       else{
     JOptionPane.showMessageDialog(null,"Wrong details" );
     }


     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel mod= (DefaultTableModel) jTable1.getModel();

        
        int j;


    try{
        Class.forName("com.mysql.jdbc.Driver");

        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/purchase","root","123");

Statement smt= con.createStatement();
          DatabaseMetaData md= (DatabaseMetaData) con.getMetaData();

  ResultSet rs= md.getTables(null,null,"%", null);
ResultSet rs1 = md.getTables(null, null, "%", null);
 //      for(int i=0; i< rs.getMetaData().getColumnCount(); i++){
   //        types[i]= rs.getString(names);
//}
jDialog2.setVisible(true);
for(j=0;rs1.next();j++);
 String tables[] = new String[j+1];
  for(j=0;rs.next();j++)
{  tables[j]= rs.getString(3);
       }

 int in= Integer.parseInt(jt1.getText());

 ResultSet rs2  = smt.executeQuery("select * from "+ tables[in-1] + ";");
 //ResultSet rs3= smt.executeQuery("Desc "+tables[in-1]+";");
 //System.out.print(rs3);
jta1.setText(null);
jl1.setText(tables[in-1]);
 while(rs2.next())
 {        //System.out.println(""+tables[in-1]);
        String id= rs2.getString("itemcode");
        String name= rs2.getString("itemname");
        String price= rs2.getString("price");
        String qty= rs2.getString("qty");
        mod.addRow(new Object[] {id, name, price, qty});
 }

  //while(a!=0){
  //System.out.println(tables[a]);
  //a++;
  //}





 //  System.out.print(nm);
    rs.close();
    rs1.close();
    rs2.close();
    smt.close();
    con.close();
    }

    catch(Exception e){
       //System.e();
        JOptionPane.showMessageDialog(null, "Error in connectivity");
    System.out.println(e.getMessage());
    }                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


 try{
        Class.forName("com.mysql.jdbc.Driver");

        //Class.forName("java.sql.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/purchase","root","123");


       Statement smt= con.createStatement();
       String nm= jl1.getText();
      int a=  smt.executeUpdate("Drop Table "+ nm + ";");

       if(a==0){
JOptionPane.showMessageDialog(null, "Order verified and out for delivery");
jDialog1.dispose();
jDialog2.dispose();

       }

    smt.close();
    con.close();
    }

    catch(Exception e){
    JOptionPane.showMessageDialog(null, "Error in connectivity");
    System.out.println(e.getMessage());
    }



// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jDialog2.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String id= jTextField1.getText();
     String pass = new String(jPasswordField1.getPassword());


     if((id.compareTo("VN71")==0) && (pass.compareTo("password")==0)){


    // JOptionPane.showMessageDialog(null, "Welcome");

        
        menus.setVisible(true);
     }

     else{
     JOptionPane.showMessageDialog(null,"Wrong details");

     }

     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
jDialog1.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
manage.setVisible(true);
 ttbm="pizza";
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from pizza ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
            DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
            while (rs.next()) {
                String n = rs.getString("Sname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");
                int qt= rs.getInt("qty");
                dtm.addRow(new Object[]{k, n, a,qt});
                dtm1.addRow(new Object[]{k, n, a,qt});
                
                //ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
manage.setVisible(true);
ttbm="indian";
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from indian ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
            DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
            while (rs.next()) {
                String n = rs.getString("Iname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("Price");
                int qt= rs.getInt("quantity");
                dtm.addRow(new Object[]{k, n, a,qt});
                dtm1.addRow(new Object[]{k, n, a,qt});

                //ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
manage.setVisible(true);
ttbm="sind";
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from sind ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
            DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
            while (rs.next()) {
                String n = rs.getString("Sname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");
                int qt= rs.getInt("qty");
                dtm.addRow(new Object[]{k, n, a,qt});
                dtm1.addRow(new Object[]{k, n, a,qt});

                //ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
manage.setVisible(true);
ttbm="chinese";
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from chinese ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
            DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
            while (rs.next()) {
                String n = rs.getString("Cname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");
                int qt= rs.getInt("qty");
                dtm.addRow(new Object[]{k, n, a,qt});
                dtm1.addRow(new Object[]{k, n, a,qt});
                //ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
manage.setVisible(true);
ttbm="beverage";
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from beverage ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
            DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
            while (rs.next()) {
                String n = rs.getString("Bname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");
                int qt= rs.getInt("qty");
                dtm.addRow(new Object[]{k, n, a,qt});
                dtm1.addRow(new Object[]{k, n, a,qt});
                //ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
manage.setVisible(true);
ttbm= "nonveg";
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "select * from nonveg ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
            DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
            while (rs.next()) {
                String n = rs.getString("Vname");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("price");
                int qt= rs.getInt("qty");
                dtm.addRow(new Object[]{k, n, a,qt});
                dtm1.addRow(new Object[]{k, n, a,qt});

                //ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
menus.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) mt.getModel();
        DefaultTableModel dtm1= (DefaultTableModel) mt1.getModel();
        int row= dtm.getRowCount();
        int row1= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        if(row1>0)
            for(int j=0;j<row1; j++)
                dtm1.removeRow(0);
        manage.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
Add.setVisible(true);
manage.dispose();                // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        String pid= jTextField4.getText();
        String pname= jTextField3.getText();
        int pri= Integer.parseInt( jTextField5.getText());
        int qty= Integer.parseInt(jTextField2.getText());
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "insert into "+ttbm+" values('"+pid+"', '"+pname+"',"+pri+","+qty+");";
            int  rs = s.executeUpdate(q);


            if(rs>0){
            JOptionPane.showMessageDialog(null,"item Inserted");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
Add.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
Delete.setVisible(true);
manage.dispose();              // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 String pid= jTextField6.getText();
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "delete from "+ttbm+" where ProductNo='"+pid+"';";
            int  rs = s.executeUpdate(q);


            if(rs>0){
            JOptionPane.showMessageDialog(null,"item deleted");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       DefaultTableModel dtm1 = (DefaultTableModel) mt1.getModel();
        int row= dtm1.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm1.removeRow(0);
        Delete.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/food", "root", "123");
            Statement s = c.createStatement();
            String q = "update "+ttbm+" set price="+jTextField8.getText()+" where ProductNo='"+jTextField7.getText()+"';";;
            int  rs = s.executeUpdate(q);


            if(rs>0){
            JOptionPane.showMessageDialog(null,"price updated");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
Update.setVisible(true);
manage.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
Update.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_BackActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Add;
    private javax.swing.JButton Back;
    private javax.swing.JDialog Delete;
    private javax.swing.JDialog Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel jl1;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextArea jta1;
    private javax.swing.JDialog manage;
    private javax.swing.JDialog menus;
    private javax.swing.JTable mt;
    private javax.swing.JTable mt1;
    // End of variables declaration//GEN-END:variables

}
